### ISSUE TITLE
URL first connection

### ISSUE THREAD

**Issue by obsid-tr** [bigbeartechworld/big-bear-umbrel#4]
Hello,
How do I get the first connection address to create the website?
the url takes me to the following page: 
<img width="712" alt="Capture d’écran 2023-08-06 à 21 04 36" src="https://github.com/bigbeartechworld/big-bear-umbrel/assets/107292614/5c77f9cb-5109-439c-ab1c-333fd2db41fc">

My URL : http://umbrel.local:7205

Thank you

**Comment by toricorn** [comment]
Hi, type /ghost at the end of the url.

Kind regards,
Tor, BigBearCommunity

**Comment by obsid-tr** [comment]
I think I must be wrong somewhere
The url takes me to the same page.
<img width="1047" alt="Capture d’écran 2023-08-06 à 22 59 27" src="https://github.com/bigbeartechworld/big-bear-umbrel/assets/107292614/7b9001bb-2723-496c-8219-ab02b6e16615">
Thank you

**Comment by toricorn** [comment]
Right, that's odd.. could you try using the ip address of the host; ip:7205/ghost instead of umbrel.local?

Kind regards
Tor
BigBearCommunity

**Comment by obsid-tr** [comment]
<img width="1440" alt="Capture d’écran 2023-08-07 à 06 49 26" src="https://github.com/bigbeartechworld/big-bear-umbrel/assets/107292614/26338ecb-eb1f-4db1-8835-2e58a5ec4b26">

**Comment by dragonfire1119** [comment]
@obsid-tr I'm just checking in on this issue. Let me know if you can try my suggestion up above.

**Comment by dragonfire1119** [comment]
I'm closing this, but if you have another issue, please feel free to open a new one.

**Comment by obsid-tr** [comment]
Hello,
Sorry for the delay, here are the logs :

big-bear-umbrel-ghost

Attaching to big-bear-umbrel-ghost_app_proxy_1, big-bear-umbrel-ghost_server_1, big-bear-umbrel-ghost_db_1, big-bear-umbrel-ghost_tor_server_1
db_1          | 2023-08-20T17:22:31.174010Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.34) starting as process 1
db_1          | 2023-08-20T17:22:31.302087Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
db_1          | 2023-08-20T17:22:37.545135Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
db_1          | 2023-08-20T17:22:40.659931Z 0 [System] [MY-010229] [Server] Starting XA crash recovery...
db_1          | 2023-08-20T17:22:40.781900Z 0 [System] [MY-010232] [Server] XA crash recovery finished.
db_1          | 2023-08-20T17:22:41.331704Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
db_1          | 2023-08-20T17:22:41.331859Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
db_1          | 2023-08-20T17:22:41.379528Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db_1          | 2023-08-20T17:22:42.246194Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
db_1          | 2023-08-20T17:22:42.275631Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.34'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
app_proxy_1   | yarn run v1.22.19
app_proxy_1   | $ node ./bin/www
app_proxy_1   | [HPM] Proxy created: /  -> http://big-bear-umbrel-ghost_server_1:2368
app_proxy_1   | Waiting for big-bear-umbrel-ghost_server_1:2368 to open...
app_proxy_1   | Ghost is now ready...
app_proxy_1   | Listening on port: 7205
server_1      | [2023-08-20 17:23:33] INFO Adding offloaded job to the queue
server_1      | [2023-08-20 17:23:33] INFO Scheduling job mentions-email-report at 27 10 * * * *. Next run on: Sun Aug 20 2023 18:10:27 GMT+0000 (Coordinated Universal Time)
server_1      | [2023-08-20 17:23:38] INFO Adding offloaded job to the queue
server_1      | [2023-08-20 17:23:38] INFO Scheduling job clean-expired-comped at 18 38 3 * * *. Next run on: Mon Aug 21 2023 03:38:18 GMT+0000 (Coordinated Universal Time)
server_1      | [2023-08-20 17:23:38] INFO Adding offloaded job to the queue
server_1      | [2023-08-20 17:23:38] INFO Scheduling job clean-tokens at 6 17 14 * * *. Next run on: Mon Aug 21 2023 14:17:06 GMT+0000 (Coordinated Universal Time)
server_1      | [2023-08-20 17:23:39] INFO Ghost booted in 24.273s
server_1      | [2023-08-20 17:23:39] INFO Adding offloaded job to the queue
server_1      | [2023-08-20 17:23:39] INFO Scheduling job update-check at 18 30 7 * * *. Next run on: Mon Aug 21 2023 07:30:18 GMT+0000 (Coordinated Universal Time)
server_1      | [2023-08-20 17:23:39] INFO Running milestone emails job on Tue Aug 22 2023 17:23:39 GMT+0000 (Coordinated Universal Time)

Thank you
